name: nexaera_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  cloud_firestore: ^4.4.3
  equatable: ^2.0.5
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  go_router: ^6.2.0
  http: ^0.13.5
  unicons: ^2.1.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/inter/Inter-Bold.ttf
          weight: 700  

    - family: SpaceGrotesk
      fonts:
        - asset: fonts/Space_Grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: fonts/Space_Grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: fonts/Space_Grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: fonts/Space_Grotesk/SpaceGrotesk-Bold.ttf
          weight: 700  
